#!/usr/bin/env bash

# Increment version code if on specified branch
branchname=`git rev-parse --abbrev-ref HEAD`
if [ "$branchname" = "release-internal" ]; then
        old_num=`cat ./ProjectSettings/ProjectSettings.asset | grep AndroidBundleVersionCode | cut -d ' ' -f 4`
        new_num=$((old_num+1))
        echo "Incrementing Android version code: $old_num > $new_num"
        sed -i -e '/AndroidBundleVersionCode/ s/:.*/: '"$new_num"'/' ./ProjectSettings/ProjectSettings.asset

        ios_ver_line=`cat ./ProjectSettings/ProjectSettings.asset | grep -n '  buildNumber:' | cut -d ':' -f 1`
        ((ios_ver_line += 1))
        old_num_ios=`cat ./ProjectSettings/ProjectSettings.asset | head -n $ios_ver_line | tail -1 | cut -d ' ' -f 6`
        new_num_ios=$((old_num_ios+1))
        echo "Incrementing iPhone version code: $old_num_ios > $new_num_ios"
        sed -i -e "${ios_ver_line}s/:.*/: 4/" ./ProjectSettings/ProjectSettings.asset
        
        git add ./ProjectSettings/ProjectSettings.asset
else
	echo "Not incrementing version code for branch $branchname."
fi
