#!/bin/env bash

target=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')

git checkout release-internal
git merge $target

# Empty commit still runs pre-commit hook updating the version code
git commit --allow-empty -m "Merge from $target: Increment APK version code"
