# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :internal do
    build
  end
  lane :beta do
    build(external: true)
  end
  lane :build do |options|
    build_app(scheme: "Unity-iPhone")
    upload_to_testflight(
      distribute_external: options[:external],
      groups: "Testers",
      demo_account_required: false,
      beta_app_review_info: {
        contact_email: "oadugmore@outlook.com",
        contact_first_name: "Owen",
        contact_last_name: "Dugmore",
        contact_phone: "7605059615",
        notes: "Thanks for trying Sync,hue! This build was automatically uploaded by Jenkins. You can review the most recent git commit messages below.\n\n" + changelog_from_git_commits(commits_count: 5)
      }
    )
  end
end
