// <copyright file="Leaderboards.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to leaderboards registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Leaderboards
    {
        private static readonly UnifiedLeaderboard s_level1_1 = new UnifiedLeaderboard("Level1_1",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "Level1_1"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI2sDRstkUEAIQAQ"
#else
            "Level1_1"
#endif
            );

        public static UnifiedLeaderboard Level1_1
        {
            get { return s_level1_1; }
        }

        private static readonly UnifiedLeaderboard s_level1_2 = new UnifiedLeaderboard("Level1_2",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "Level1_2"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI2sDRstkUEAIQAw"
#else
            "Level1_2"
#endif
            );

        public static UnifiedLeaderboard Level1_2
        {
            get { return s_level1_2; }
        }

        private static readonly UnifiedLeaderboard s_level1_3 = new UnifiedLeaderboard("Level1_3",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "Level1_3"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI2sDRstkUEAIQBA"
#else
            "Level1_3"
#endif
            );

        public static UnifiedLeaderboard Level1_3
        {
            get { return s_level1_3; }
        }

        private static readonly UnifiedLeaderboard s_level1_4 = new UnifiedLeaderboard("Level1_4",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "Level1_4"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI2sDRstkUEAIQBQ"
#else
            "Level1_4"
#endif
            );

        public static UnifiedLeaderboard Level1_4
        {
            get { return s_level1_4; }
        }

        private static readonly UnifiedLeaderboard s_level1_5 = new UnifiedLeaderboard("Level1_5",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "Level1_5"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI2sDRstkUEAIQBg"
#else
            "Level1_5"
#endif
            );

        public static UnifiedLeaderboard Level1_5
        {
            get { return s_level1_5; }
        }

        private static readonly UnifiedLeaderboard s_level1_6 = new UnifiedLeaderboard("Level1_6",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "Level1_6"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI2sDRstkUEAIQBw"
#else
            "Level1_6"
#endif
            );

        public static UnifiedLeaderboard Level1_6
        {
            get { return s_level1_6; }
        }

        private static readonly UnifiedLeaderboard s_level1_7 = new UnifiedLeaderboard("Level1_7",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "Level1_7"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI2sDRstkUEAIQCA"
#else
            "Level1_7"
#endif
            );

        public static UnifiedLeaderboard Level1_7
        {
            get { return s_level1_7; }
        }

        private static readonly UnifiedLeaderboard s_level1_8 = new UnifiedLeaderboard("Level1_8",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "Level1_8"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI2sDRstkUEAIQCQ"
#else
            "Level1_8"
#endif
            );

        public static UnifiedLeaderboard Level1_8
        {
            get { return s_level1_8; }
        }

        private static readonly UnifiedLeaderboard s_level2_1 = new UnifiedLeaderboard("Level2_1",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "Level2_1"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI2sDRstkUEAIQCg"
#else
            "Level2_1"
#endif
            );

        public static UnifiedLeaderboard Level2_1
        {
            get { return s_level2_1; }
        }

        private static readonly UnifiedLeaderboard s_level2_2 = new UnifiedLeaderboard("Level2_2",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "Level2_2"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI2sDRstkUEAIQCw"
#else
            "Level2_2"
#endif
            );

        public static UnifiedLeaderboard Level2_2
        {
            get { return s_level2_2; }
        }

        private static readonly UnifiedLeaderboard s_level2_3 = new UnifiedLeaderboard("Level2_3",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "Level2_3"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI2sDRstkUEAIQDA"
#else
            "Level2_3"
#endif
            );

        public static UnifiedLeaderboard Level2_3
        {
            get { return s_level2_3; }
        }

        private static readonly UnifiedLeaderboard s_level2_4 = new UnifiedLeaderboard("Level2_4",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "Level2_4"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI2sDRstkUEAIQDQ"
#else
            "Level2_4"
#endif
            );

        public static UnifiedLeaderboard Level2_4
        {
            get { return s_level2_4; }
        }

        private static readonly UnifiedLeaderboard s_level2_5 = new UnifiedLeaderboard("Level2_5",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "Level2_5"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI2sDRstkUEAIQDg"
#else
            "Level2_5"
#endif
            );

        public static UnifiedLeaderboard Level2_5
        {
            get { return s_level2_5; }
        }

        private static readonly UnifiedLeaderboard s_level2_6 = new UnifiedLeaderboard("Level2_6",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "Level2_6"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI2sDRstkUEAIQDw"
#else
            "Level2_6"
#endif
            );

        public static UnifiedLeaderboard Level2_6
        {
            get { return s_level2_6; }
        }

        private static readonly UnifiedLeaderboard s_level2_7 = new UnifiedLeaderboard("Level2_7",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "Level2_7"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI2sDRstkUEAIQEA"
#else
            "Level2_7"
#endif
            );

        public static UnifiedLeaderboard Level2_7
        {
            get { return s_level2_7; }
        }

        private static readonly UnifiedLeaderboard s_level2_8 = new UnifiedLeaderboard("Level2_8",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "Level2_8"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI2sDRstkUEAIQEQ"
#else
            "Level2_8"
#endif
            );

        public static UnifiedLeaderboard Level2_8
        {
            get { return s_level2_8; }
        }

        public static string GetPlatformID(string internalId)
        {
            return s_leaderboardDictionary.ContainsKey(internalId)
                ? s_leaderboardDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedLeaderboard> s_leaderboardDictionary = new Dictionary<string, UnifiedLeaderboard>
        {
            { "Level1_1", s_level1_1 },
            { "Level1_2", s_level1_2 },
            { "Level1_3", s_level1_3 },
            { "Level1_4", s_level1_4 },
            { "Level1_5", s_level1_5 },
            { "Level1_6", s_level1_6 },
            { "Level1_7", s_level1_7 },
            { "Level1_8", s_level1_8 },
            { "Level2_1", s_level2_1 },
            { "Level2_2", s_level2_2 },
            { "Level2_3", s_level2_3 },
            { "Level2_4", s_level2_4 },
            { "Level2_5", s_level2_5 },
            { "Level2_6", s_level2_6 },
            { "Level2_7", s_level2_7 },
            { "Level2_8", s_level2_8 },
        };
    }
}
